import React from "react";
import { Navbar, Text } from "@nextui-org/react";
import Head from "next/head";
import Link from "next/link";
import Styles from "../../styles/Home.module.css";
export default function Layout({ children, title }) {
  const collapseItems = [
    { title: "Home", href: "/" },
    { title: "Project", href: "/" },
    { title: "Team", href: "/" },
    { title: "Contact", href: "/auth/signUp" },
  ];
  return (
    <div>
      <Head>
        <title>{title ?? ""}Febproject</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar
        isBordered
        variant={"static"}
        maxWidth="fluid"
        css={{ backgroundColor: "$myColor" }}
        className="fixed bg-opacity-25"
      >
        <div className="flex justify-center lg:justify-between w-full">
          <div className="flex gap-4">
            <Navbar.Toggle
              className="lg:hidden absolute left-4"
              aria-label="toggle navigation"
            />
            <h1 className="text-2xl font-bold">Febproject</h1>
          </div>
          <div className="hidden lg:flex gap-4">
            {collapseItems.map((e, i) => {
              return (
                <Link key={i} href={e.href}>
                  {e.title}
                </Link>
              );
            })}
          </div>
        </div>
        <Navbar.Collapse>
          {collapseItems.map((item, index) => (
            <Navbar.CollapseItem key={item}>
              <Link
                color="inherit"
                css={{
                  minWidth: "100%",
                }}
                href={item.href}
              >
                {item.title}
              </Link>
            </Navbar.CollapseItem>
          ))}
        </Navbar.Collapse>
      </Navbar>
      <main>{children}</main>
      <footer className="text-center">2023, Febriqgal</footer>
    </div>
  );
}
